START_TIME_MAX_DELAY = 4

TABLE_CAPACITY = 15
NUMBER_OF_DISHWASHERS = 2

CONSUMMATION_TIME = 12
CONSUMMATION_TIME_MARGIN_ERROR = 4
TABLEWARE_DISPOSAL_TIME = 2

# simulation execution related variables
SIMULATION_FACTOR = 1
SIMULATION_INITIAL_TIME = 0
